name: CI

on: [pull_request, push]

env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: --deny warnings

jobs:
  style:
    name: Check basic style
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - run: ./.github/check-basic-style.sh

  check:
    name: 'Build & test'
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - run: cargo build
    - run: cargo test
    - run: cargo doc
